<?php
$endereco = $this->customFields[$this->ID]['piso'] . ' - Loja nº ' . $this->customFields[$this->ID]['numero_loja'];
$telefone = $this->customFields[$this->ID]['telefone'];
?>
<div class="masonry-item">
        <a href="<?= $this->permalink ?>" title="<?= $this->title; ?>" class="wpmg_image_featured">
        <?php echo $this->thumb ?>
        </a>
    <div class="masonry-item-inner">
        <h3><a href="<?= $this->permalink ?>" title="<?= $this->title ?>"><?= $this->title  ?></a></h3>
        <h6><?= $this->segmentos ?></h6>
        <p><img src="<?= $this->site_url ?>/wp-content/uploads/2016/08/pin.svg" />  <?= $endereco ?></p>
        <p><img src="<?= $this->site_url ?>/wp-content/uploads/2016/08/telefone.svg" />  <?= $telefone ?></p>
    </div>
</div>
